### ISSUE TITLE
Property "failover.backhaul" missing from modem_information reponse (Nighthawk M1 modem)

### ISSUE THREAD

**Issue by code-to-joy** [amelchio/eternalegypt#18]
This seems to be specific for the Netgear MR1100 (Nighthawk M1) device. 

When returning the model.json data from the modem, the property "failover.backhaul" is missing from the returned dictionary. When trying to populate the .upstream property of the resulting object, the dictionary value does not exist, and an error occurs.

Note that to not have the error handling code catch and swallow this exception, I made changes to raise the original error. Without those changes the only error out will most likely be this:

`Traceback (most recent call last):
  File "C:\Users\user\OneDrive - QlikTech Inc\Code\eternalegypt-master\eternalegypt-master\examples\status.py", line 55, in <module>
    asyncio.get_event_loop().run_until_complete(get_information())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Code\eternalegypt-master\eternalegypt-master\examples\status.py", line 24, in get_information
    result = await modem.information()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py", line 72, in wrapper
    raise Error(str(function))
eternalegypt.eternalegypt.Error: <function LB2120.information at 0x0000027756EB0160>`

Without the error handling swalling the exception; this is the real error:

`    <module>	C:\Code\eternalegypt-master\eternalegypt-master\examples\status.py	55		
    run_until_complete	C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py	608		
    get_information	C:\Code\eternalegypt-master\eternalegypt-master\examples\status.py	24		
    wrapper	C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py	62		
    information	C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py	289		
    _build_information	C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\eternalegypt\eternalegypt.py	243		
KeyError: 'backhaul'				`

Please note that the rows in this call stack might not add up to the original source code of eternalegypt.py, since this is running a modified version. The original row of this error is 231. 

I had a suspicion that this was a configuration symptom, but since the whole rest of the "failover" object body is still returned, and this value is the only one missing (it is not missing from the other two tested modems), so it seem unlikely that this is related to configuration. 

Steps to reproduce: 
1. Run script status.py against a Netgear Nighthawk M1 modem

Suggested fix: 
`
if 'backhaul' in data['failover']:
    result.upstream = data['failover']['backhaul']
`

**Comment by amelchio** [comment]
Both issues should be fixed now in 0.0.11, can you verify that it works?

**Comment by code-to-joy** [comment]
@amelchio Just tested, and verified that it's your changes running, and it works. Tested inbox.py and status.py, and everything worked as expected.

**Comment by amelchio** [comment]
Thanks, that's great.

I will make a PR for Home Assistant within a few days ... if you want to beat me to it, feel free.

**Comment by amelchio** [comment]
Now merged into Home Assistant for the 0.103 beta, home-assistant/home-assistant#29446.
