### ISSUE TITLE
Is it possible to add 'time connected'?

### ISSUE THREAD

**Issue by Swiftnesses** [amelchio/eternalegypt#22]
Hello,

Thank you for this great module.

Is it possible to add the connected time, so I can monitor my uptime?

Many thanks in advance.

**Comment by amelchio** [comment]
If it is in the admin interface, it can be added. However, I am currently taking a break from implementing new features.

If you are using Home Assistant, you can probably use the existing `binary_sensor.mobile_connected` to build your own timer.

**Comment by amelchio** [comment]
I checked now and I don't see that information in the returned data, sorry.
