### ISSUE TITLE
Usecase with Home Assistant

### ISSUE THREAD

**Issue by tbgoose** [amelchio/eternalegypt#36]
Hi all

Just added a Netgear LM1200 as LTE WAN failover into my network after an extended period of outage for FTTH NBN.

I am new python, could anyone explain the use case for this project and Home Assistant? How would I go about adding elements of it to HA, and then how do I interact with it afterwards?

Main use case for me is notification or tracking of when LTE WAN failover occurs, and then running a script I have on HA and unraid to turn off bandwidth heavy applications.

Cheers

**Comment by amelchio** [comment]
This library is already supported in Home Assistant with the [Netgear LTE](https://www.home-assistant.io/integrations/netgear_lte/) integration.

If you need support, you will be better served by the HA discussion forum :)

**Comment by tbgoose** [comment]
Awesome, thanks. I have found and am using that now. FYI it doesn't seem like there is a way to pull the WAN IP address when using the integration, is that correct?

It is included in your project under the status.py, but none of the sensors relate to it

**Comment by amelchio** [comment]
I believe you are right. I got discouraged from working on Home Assistant before all the available values were implemented as sensors.

It seems like there is a new maintainer for the Netgear LTE integration now so maybe you could be successful with a feature request.
